---
- name: "Playbook to Add Key to VM's"
  hosts: hosts_to_add_key
  vars:
    - status : "present"
    - key : "/home/ubuntu/.ssh/id_rsa.pub"

  tasks:

  - name: "Copy the authorized key file from"
    authorized_key:
      user: "{{ansible_user}}"
      state: "{{status}}"
      key: "{{ lookup('file', '{{ key }}')}}"

