version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.19.3
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  test:
    jobs:
      - test
