---
- name: "Playbook to Add Key to VM's"
  hosts: hosts
  vars:
    - status : "present"
    - key : "/home/centos/.ssh/id_rsa.pub"

  tasks:

  - - name: "Make Keys dir"
    shell: mkdir keys
 
  - name: "Copy the authorized key file from"
    authorized_key:
      user: "{{ansible_user}}"
      state: "{{status}}"
      key: "{{ lookup('file', '{{ key }}')}}"

