---
- name: "Playbook to Add Key to VM's"
  hosts: hosts
  vars:
    - status : "present"

  tasks:

  - name: "Copy the authorized key file from"
    authorized_key:
      user: "{{ansible_user}}"
      state: "{{status}}"
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

