---
- name: "Playbook to install VM's"
  hosts: hosts
  vars:
    - status : "present"

  tasks:
  - name: "Install Global Pharmacy Demo (GPD)"
    shell: cd test/tf-nimoy/remote/benchmarksql; /home/centos/apache-ant-1.9.16/bin/ant;
  
  - name: "Install io"       
    shell: python3 -c "$(curl -fsSL https://oscg-io-download.s3.amazonaws.com/REPO/install.py)"; 
    
  - name: "Install Postgres Client"
    shell: cd oscg; ./io install pg{{ PGV }};

  - name: "Securely Saving PG Passwords from Nodes"
    copy: src="{{ PGFile }}" dest=/home/centos/.pgpass   
 
  - name: "Finalizing PG Pass"
    shell: touch /home/centos/.pgpass; chmod 600 /home/centos/.pgpass;

  - name: "Regionalizing Default GPD Data"
    copy: src="{{ DEMSQL }}" dest=demo.sql
