---
- name: "Playbook to install VM's"
  hosts: hosts
  vars:
    - status : "present"

  tasks:
  - name: "Install io"       
    shell: cd /db; python3 -c "$(curl -fsSL https://oscg-io-download.s3.amazonaws.com/REPO/install.py)" 
    
  - name: "Install pg"
    shell: cd /db/oscg; ./io install pg{{ PGV }};
    
  - name: "Create pass file"
    shell: echo {{ PASS }} > /db/oscg/pg{{ PGV }}/.pgpass

  - name: "Start io"
    shell: cd /db/oscg; ./io start pg{{ PGV }} -y -d demo {{ ':' }} tune pg{{ PGV }} {{ ':' }} install spock -d demo {{ ':' }} install prompgexp --start

  - name: "Copy final pass"
    copy: src="{{ PGFile }}" dest=/home/centos/.pgpass

  - name: "Set up pgpass"
    shell: touch /home/centos/.pgpass; chmod 600 /home/centos/.pgpass;
