---
- name: "Playbook to install VM's"
  hosts: hosts_to_io
  vars:
    - status : "present"

  tasks:
  - name: "Install bmsql"
    shell: cd test/tf-nimoy/remote/benchmarksql; /home/centos/apache-ant-1.9.16/bin/ant;
  
  - name: "Install io"       
    shell: python3 -c "$(curl -fsSL https://oscg-io-download.s3.amazonaws.com/REPO/install.py)"; 
    
  - name: Install pg"
    shell: cd oscg; ./io install pg{{ PGV }};
    
  - name: "Set up pgpass"
    shell: touch /home/centos/.pgpass; chmod 600 /home/centos/.pgpass; 
